services:
  - type: web
    name: healthpredict-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    branch: main
    runtime: python
